# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    exclude-paths:
      - klass-forvaltning  # Versions can't be upgraded due to Vaadin
      - klass-solr  # Not necessary to update
      - klass-api  # Has its own config below
      - klass-shared  # Has its own config below
      - klass-mail  # Has its own config below
    schedule:
      interval: "weekly"
    groups:
      klass-root:
        ignore:
          # Don't attempt to automatically update to Spring v4
          - dependency-name: "org.springframework.*:*"
            update-types: [ "version-update:semver-major" ]
        patterns:
          - "*"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/klass-api" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      klass-api:
        ignore:
          # Don't attempt to automatically update to Spring v4
          - dependency-name: "org.springframework.*:*"
            update-types: [ "version-update:semver-major" ]
        patterns:
          - "*"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/klass-shared" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      klass-shared:
        ignore:
          # Don't attempt to automatically update to Spring v4
          - dependency-name: "org.springframework.*:*"
            update-types: [ "version-update:semver-major" ]
        patterns:
          - "*"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/klass-mail" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      klass-mail:
        ignore:
          # Don't attempt to automatically update to Spring v4
          - dependency-name: "org.springframework.*:*"
            update-types: [ "version-update:semver-major" ]
        patterns:
          - "*"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
